### PR TITLE
NoSelectAllDAO - improving validation and testing order and predicate

### PR DESCRIPTION
**Pull request by marcogbarcellos**
- before inserting the required predicates `True` and `False`, I was getting `cannot set isInstance of undefined`. 

- created unit test to validate predicate and orderby.

### CODE REVIEW

**Comment by kgrgreer** [comment]
Something else is wrong. The " this.True && " check shouldn't be required since True and False are required on lines 25 and 26.

**Comment by adamvy** [comment]
Had you pulled recently when you were getting those errors?  I added the requires earlier tonight.

**Comment by kgrgreer** [comment]
Hahaha, that would explain it. You don't pull for a couple hours and someone goes and fixes the code ahead of you.

**Comment by marcogbarcellos** [comment]
You're right guys! perhaps only the test worths it. thanks.

**Comment by kgrgreer** [comment]
Update your patch to just contain the test and I'll merge it.

**Pull request closed without merging**
