### PR TITLE
Fix ClassCastException

### PR DESCRIPTION
**Pull request by lchanmann**
## Ref
- https://nanopay.atlassian.net/browse/NP-2139

## Changes
- Fix ClassCastException in IN mlang
- Safety check to exclude null capability from grant path

### CODE REVIEW

**Comment by lchanmann** [comment]
@kgrgreer @jlhughes please review when you have a chance.

**Review by jlhughes — COMMENTED** [review]
@kgrgreer can you post review please. I need this now.

**Comment by kgrgreer** [comment]
Wasn't this already fixed in:

commit 9b0976eb43a4b1704e77cc703de8779416d798f2
Author: Kevin Greer <kgrgreer@gmail.com>
Date:   Fri Sep 25 12:44:39 2020 -0400

    Fix ClassCastException being thrown in IN mlangs.

**Comment by lchanmann** [comment]
arg2 of IN can be a list and it throws ClassCastException when casting a list to object array.

**Comment by kgrgreer** [comment]
I see. Thx.

**Pull request merged**
