### PR TITLE
Add cash in cash out for all accounts view

### PR DESCRIPTION
**Pull request by KateMengjunXia**

### CODE REVIEW

**Comment by adamvy** [comment]
CICO is nanopay specific. It shouldn't be referenced from the foam2 repository.

**Comment by jlhughes** [comment]
@TW80000 can you help @KateMengjunXia assuming we have SME DAOController logic.  How has this type of thing been implemented on the Ablii side? I'm assuming we extend the DAOController.

**Comment by TW80000** [comment]
@jlhughes For sure

@KateMengjunXia We do this in Ablii for 4 pages: Banking, Contacts, Payables, and Receivables. The way to do it is to add a new class in the nanopay repo that extends `'foam.comics.DAOController'`. Then you can create a new Menu in the `menus` journal file in nanopay, set the handler to a DAOMenu, and set the `customDAOController` property to your new custom DAO controller extension. Then you can add whatever properties you want to your own controller. See [menus.jrl](https://github.com/nanoPayinc/NANOPAY/blob/development/nanopay/src/net/nanopay/sme/menus.jrl#L8) and [ContactController](https://github.com/nanoPayinc/NANOPAY/blob/development/nanopay/src/net/nanopay/contacts/ContactController.js) for examples.

**Comment by TW80000** [comment]
Please make these changes in the nanopay repo.

**Pull request closed without merging**
