### PR TITLE
Add async support on context menu action isEnabled for TableView

### PR DESCRIPTION
**Pull request by lchanmann**
Needed for: https://github.com/nanoPayinc/NANOPAY/pull/5560/commits/dbb9ba0b2aaed06f676fe746baec0aa0570df036

### CODE REVIEW

**Comment by kgrgreer** [comment]
Does this still work for isEnabled() implementations which aren't asynchronous?

**Comment by lchanmann** [comment]
Yes, it works fine.

**Comment by jlhughes** [comment]
@lchanmann you'll need to undo the merge of the freeze business branch.

**Comment by lchanmann** [comment]
@jlhughes https://github.com/nanoPayinc/NANOPAY/pull/5560 wasn't merged yet

**Review by jlhughes — APPROVED** [review]

**Pull request merged**
