### PR TITLE
Different heights dropdown text fields

### PR DESCRIPTION
**Pull request by skanderturki**
In some user interfaces (example: Operations -> Users), drop down lists and text inputs have different hights.

### CODE REVIEW

**Comment by kgrgreer** [comment]
LGTM

**Review by TW80000 — CHANGES_REQUESTED** [review]
This doesn't look right to me. The way we make height consistent across inputs is by getting all inputs to respect the `inputHeight` value that comes from the `Theme` model.

Not only that, but not all views of properties are inputs, so forcing all of them to a fixed height doesn't make sense.

Could you provide a screenshot of where the heights look inconsistent? The users screen looks correct as is to me.

**Comment by skanderturki** [comment]
Yes
Screen Shot 2019-10-10 at 3 09 20 PM

**Comment by skanderturki** [comment]
Here status and compliance have a 35px height while name and id fore example have a 45px height

**Comment by TW80000** [comment]
@skanderturki https://github.com/foam-framework/foam2/pull/2665 has been merged and this issue should have been fixed by it. Can you please check and close this PR if the issue has been fixed?

**Comment by skanderturki** [comment]
ok

**Comment by TW80000** [comment]
Fixed by #2665

**Pull request closed without merging**
