### PR TITLE
Colour scheme support on theme

### PR DESCRIPTION
**Pull request by TW80000**
* Adds properties to Theme that represent a colour palette
* Removes the old colour properties and updates all references to reference the new colours

The default FOAM colour scheme is pictured below.

Screen Shot 2019-06-17 at 3 43 27 PM

### CODE REVIEW

**Comment by adamvy** [comment]
My main concern with this PR is that if breaks all views when not running under nanos.  We should ensure that those macros _always_ expand to reasonable defaults even if you're not running under nanos.

**Comment by TW80000** [comment]
> My main concern with this PR is that if breaks all views when not running under nanos. We should ensure that those macros _always_ expand to reasonable defaults even if you're not running under nanos.

Yeah, I'll change everything to the form `/*%WHATEVER%*/ #abc123`.

**Comment by adamvy** [comment]
Sounds good

**Comment by TW80000** [comment]
> Sounds good

@adamvy Updated.

**Pull request merged**
