### PR TITLE
Added generated file disclaimer to java interface

### PR DESCRIPTION
**Pull request by TanayParikh**
- Disclaimer from `src/foam/java/Class.js` added to interface

Reference:
```
// WARNING: GENERATED CODE, DO NOT MODIFY BY HAND!
```

- Minor change to assist in identifying generated files (as already in use with Class and Enum)

### CODE REVIEW

**Comment by kgrgreer** [comment]
Maybe this would be a better warning (also, no need to include adam's name):

o.out('// WARNING: GENERATED CODE, DO NOT MODIFY BY HAND!\n');

**Comment by TanayParikh** [comment]
Sure, I'll update Class.js as well in accordance.

Edit: Updated

**Comment by adamvy** [comment]
I was trying to pad my author stats but including my name in all files generated using my tool :D

**Comment by kgrgreer** [comment]
Hey, it worked for me for 10 years ;-).

**Comment by TanayParikh** [comment]
CI test issue should be resolved with d921cc374f1a186248b217bd9e0bebffe817bbc4

**Pull request merged**
