### PR TITLE
Prevented the generation of ClassInfo for AbstractFObject

### PR DESCRIPTION
**Pull request by kirkeaton**
In some rare cases: the `getOwnClassInfo` static method in AbstractFObject was being called instead of the subclasses.

### CODE REVIEW

**Comment by kgrgreer** [comment]
Should we not generate for all Abstract classes, not just AbstractFObject?

**Comment by kirkeaton** [comment]
@kgrgreer I don't think so. It could happen with non-abstract classes being subclassed too.

**Comment by mcarcaso** [comment]
I'm confused why this is needed. When and why does this get called when you
don't expect it to?

**Comment by kirkeaton** [comment]
@mcarcaso Kenny was the only one experiencing this issue and I have not been able to reproduce this at all. This fixes it for him.

**Comment by mcarcaso** [comment]
I worry this could be masking a deeper issue is all. This should be
investigated because it's not clear why it's needed.

**Comment by mcarcaso** [comment]
Could it be from calling the method on a hand written Java class that
extends abstractfobject?

**Pull request merged**
