### PR TITLE
[NP-2792] Unify CapabilityWizardlet

### PR DESCRIPTION
**Pull request by KernelDeimos**
Composition + Polymorphism solution to duplicate code: https://nanopay.atlassian.net/browse/NP-2792

Issue was `CapabilityWizardlet` and `CapableObjectWizardlet` had their own implementations of save, and any CapabilityWizardlet subclasses (MinMaxCapabilityWizardlet) would need to have a duplicate extending the other one (CapableMinMaxCapabilityWizardlet).

By creating an interface (WizardletDataController) for `save`,`cancel`,`load`, it became possible to extend just CapabilityWizardlet and provide an implementation for WizardletDataController to handle the separate Capability/Capable cases.
UnifyCapableWizardletBeforeAfter

### CODE REVIEW

**Review by jlhughes — APPROVED** [review]

**Review by Nauna — COMMENTED** [review]
pulled branch and running with master merged and latest dev.
Getting build error:
```/Users/anna/Documents/NANOPAY3/NANOPAY/build/src/java/foam/nanos/crunch/ui/UCJWizardletDataController.java:6: 
error: UCJWizardletDataController is not abstract and does not override abstract method load() in WizardletDataController

public class UCJWizardletDataController implements foam.u2.wizard.WizardletDataController, foam.core.FObject {
       ^
```

although the method is there - trying something - if it works will delete this comment

**Comment by KernelDeimos** [comment]
> pulled branch and running with master merged and latest dev.
> Getting build error:
> 
> ```
> error: UCJWizardletDataController is not abstract and does not override abstract method load() in WizardletDataController
> 
> public class UCJWizardletDataController implements foam.u2.wizard.WizardletDataController, foam.core.FObject {
>        ^
> ```
> 
> although the method is there - trying something - if it works will delete this comment

Probably needs `flags: ['web']` in the model... I'll try that

**Comment by KernelDeimos** [comment]
`flags` fixes it

**Review by Nauna — APPROVED** [review]

**Comment by kgrgreer** [comment]
Ctrl/Controller usually has a different meaning in FOAM and other MVC frameworks. How about naming it WAO (pronounced WOW), for Wizardlet Access Object, which would draw the analogy of being similar to a DAO, in that it is an abstract storage mechanism.

**Pull request merged**
