### PR TITLE
Modified Session Model To Account For Proxied Requests

### PR DESCRIPTION
**Pull request by tharmaman**
This PR is in regards to ticket [CPF-867](https://nanopay.atlassian.net/browse/CPF-867).

Rather than making a new whitelistedXForwardedForDAO, Joel and I decided that it would be unnecessary as we could just modify the Session model instead.

Here are the following changes that were made:
1. Rather than the Session model only including one remoteHost property which stores the IP returned from req.getRemoteHost(), I replaced that property with two new properties: **sourceHost** and **proxyHost**.

**sourceHost** and **proxyHost** were put in place to account for requests who have the **X-Forwarded-For** header:
     * sourceHost would be the IP detailed in the X-Forwarded-For header
     * proxyHost would be what ever req.getRemoteHost returns (which is always the last node that sent the request which in this case is the proxy)
     * in cases without proxies, sourceHost would be req.getRemoteHost and proxyHost would be null

2. Modified the logic in **AuthWebAgent.java** and **SessionServerBox.java** which previously contained session.getRemoteHost() to account for sourceHost and proxyHost by factoring in cases for proxies and non-proxies

**BONUS**: Added "_android/nanos_example_client/.settings/_" to the foam2 .gitignore after talking to numerous people facing the same problem of always having to remove this file in particular from git in order to make a proper commit to foam2

### CODE REVIEW

**Comment by jlhughes** [comment]
Regarding whitelist, since the Session is updated and saved to the SessionDAO we can use the RuleEngine to enforce the whitelist.

**Comment by kgrgreer** [comment]
This approach basically implements the same logic twice, once for WebAgents and once for Boxes, but if we instead just handled this in foam.nanos.jetty.HttpServer then we would only have to do this once. Also, that object is where we already configure other HTTP server options, so would be a reasonable place to configure the whitelist. Also, doing it there would ensure that unauthenticated services would also get the correct IP-address. Jetty already provides code to do this: https://www.eclipse.org/jetty/javadoc/9.4.8.v20171121/org/eclipse/jetty/server/ForwardedRequestCustomizer.html which we could install in HttpServer if the whitelist is set.

**Review by kgrgreer — CHANGES_REQUESTED** [review]
See comments in discussion.

**Comment by jlhughes** [comment]
@tharmaman we can close this PR yes?

**Pull request closed without merging**
