### PR TITLE
Web Fetch API: Deal with missing headers API on Edge

### PR DESCRIPTION
**Pull request by mdittmer**

### CODE REVIEW

**Review by jacksonic — CHANGES_REQUESTED** [review]
Could this be polyfilled on the Headers class itself?

**Comment by mdittmer** [comment]
It could, but that would be more code, unless we have a spec-compliant Iterator implementation in FOAM already.

**Review by jacksonic — APPROVED** [review]

**Comment by jacksonic** [comment]
That's a pain. Tell them to stop adding new collection interfaces; this isn't Python.

**Comment by mdittmer** [comment]
I agree. This is `# Temporary I hope, hope, hope`. Presumably, Edge will fix the bug and we can remove this rather than investing in our own polyfill implementation.

**Pull request merged**
