### PR TITLE
Add a calendar date picker to the u2 view library.

### PR DESCRIPTION
**Pull request by mcarcaso**
It's not super pretty but I prefer this over most date pickers I've used before:

image

Demo link if you run `python -m SimpleHTTPServer` from cmd line:
`http://localhost:8000/index.html?model=foam.u2.view.date.DateTimePicker`

### CODE REVIEW

**Comment by jlhughes** [comment]
@mcarcaso with @kgrgreer port of the foam1 calendar to foam2 can we close this PR?

**Comment by kgrgreer** [comment]
I would prefer Mike's if we can update it to Logan's UX design. The foam1
one brings in a lot of dependencies.

**Comment by jlhughes** [comment]
@mcarcaso UX styling is here: https://zpl.io/2p4BK8E
Suspect you'll need to ask for access.

**Comment by mcarcaso** [comment]
We can certainly update the UX to match Logan's designs later. In the meantime at least we have a functional but ugly date picker.

**Pull request merged**
