### PR TITLE
Move all notification nspecs to package local services file

### PR DESCRIPTION
**Pull request by jlhughes**
Add localNotificationSettings nspec

### CODE REVIEW

**Comment by TW80000** [comment]
If I recall correctly, @mcarcaso told me that doing this in foam breaks the foam build script/tool. Apparently it's only the nanopay build script that looks in subdirectories for now. I haven't tested this myself though, and I guess we could always just improve the foam build tool, but I thought I'd mention it.

**Comment by kgrgreer** [comment]
Good to know, but I don't think anybody is building FOAM alone anyway, and
if that is broken, then we should fix it. Can you assign a low-priority
ticket to Eric to test/fix?

**Comment by TW80000** [comment]
> Good to know, but I don't think anybody is building FOAM alone anyway, and if that is broken, then we should fix it. Can you assign a low-priority ticket to Eric to test/fix?

@kgrgreer will do.

**Comment by TW80000** [comment]
https://nanopay.atlassian.net/browse/CPF-3954

**Comment by mcarcaso** [comment]
Sorry I don’t really recall this but before I lost access to your repo you
were also using the JS build tool to bundle your app into a single payload.
If that still works then you should be good here. I can’t think of why this
change would break that off the top of my head but anything is possible.

**Pull request merged**
