### PR TITLE
Sink interface change: put, remove args: (sub, obj) => (obj, sub)

### PR DESCRIPTION
**Pull request by mdittmer**
Towards #301. 25abf392efdc6db3d5b4e303ac771bed19d68748 changed the `Sink.put()` and `Sink.remove()` to accept a subscription object as the first paramter. The idea was to make these methods closer to the `Listener` interface. Subsequent discussions built a consensus that similarity to `Listener` is less important that putting the most-used paramter first (and not breaking existing consumers of `Sink`). This change effectively reverts the "change the Sink interface" parts of 25abf392efdc6db3d5b4e303ac771bed19d68748.

### CODE REVIEW

**Comment by jacksonic** [comment]
I agree it is certainly simpler to put the optional argument last.

**Comment by mdittmer** [comment]
FWIW, I'm not sure whether the argument is strictly optional (in the interface contract sense). However, it is rarely used by `Sink` implementations.

**Comment by jacksonic** [comment]
Right, "frequently unused" from the Sink's point of view. Callers must
supply something.

**Comment by adamvy** [comment]
fine with me

**Pull request merged**
