### PR TITLE
Add missing test class

### PR DESCRIPTION
**Pull request by jlhughes**
CPF-2915 #time 30m

### CODE REVIEW

**Review by TW80000 — COMMENTED** [review]
I tried to reproduce the issue and notice that I only get the console error when building using the liveScriptBundler. When I build with `./build.sh -w` then the tests table loads correctly with no errors. So we might consider the bug with the liveScriptBundler instead. That said, until we can fix the issue with the liveScriptBundler, we can merge this. Although I think `TimeOfDayScheduleTest` should be added as well.

**Comment by jlhughes** [comment]
I'll get Eric to create tickets.

**Comment by KernelDeimos** [comment]
I actually had IntervalScheduleTest and TimeOfDaySchedule test both added in their own tests.jrl already (src/foam/nanos/cron/tests.jrl) - do I need to add them to both places? @TW80000

**Comment by TW80000** [comment]
> I actually had IntervalScheduleTest and TimeOfDaySchedule test both added in their own tests.jrl already (src/foam/nanos/cron/tests.jrl) - do I need to add them to both places? @TW80000

@KernelDeimos Yeah, you need to list both in `classes.js` if you want FOAM to generate Java code for them afaik.

**Pull request merged**
